# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "my_agent_pool"
  stages:
    Stage: one stage
  jobs:
    job : one  
    steps:
      script: echo Hello from my first pipeline!


